---
title: "MMM_with_Robyn"
format:
  html:
    theme: default
    toc: true
    toc-title: 目次
    number-sections: true
    self-contained: true
execute: 
  echo: true     # コードを出力に含めるか
  cache: false   # 実行結果のキャッシュを保持するか
  prompt: false  # コードの先頭に">"を表示するか
  tidy: false    # コードの整形を行うか
  comment: NA    # コードの先頭に付加される文字列
  message: false # コードが出力するメッセージを含めるか
  warning: false # コードが出力する警告を含めるか
  error: false   # エラーメッセージを表示するか
editor_options: 
  chunk_output_type: console
---

# はじめに

-   この資料はRobynでのMMMに関するドキュメントです

# 環境設定

-   `nevergrad`用にminicondaをインストール

-   `Robyn`用の仮想環境を作成してセットアップしておきます

```{r}
#| eval: false

# condaでrobyn用の仮想環境を作成(初回は実行)
library(reticulate)
install_miniconda()
conda_create('mmm_robyn')
conda_install(envname = 'mmm_robyn', packages = 'nevergrad', pip = TRUE)
```

```{r}
# reticulateでconda環境を指定(vscodeとrstudioでパスが異なるので注意)
library(reticulate)
# Sys.setenv(RETICULATE_PYTHON = "/home/rstudio/.local/share/r-miniconda/envs/mmm_robyn/bin/python") # for rstudio
Sys.setenv(RETICULATE_PYTHON = "/root/.local/share/r-miniconda/envs/mmm_robyn/bin/python") # for vscode
use_miniconda('mmm_robyn', required = TRUE) # py_discover_config()
```

-   `Robyn`に必要な諸々の設定

```{r}
# ライブラリ
if (!require("pacman")) install.packages("pacman"); library(pacman)
p_load(tidyverse)
p_load(magrittr)
p_load(janitor)
p_load(skimr)
p_load(Robyn) # packageVersion("Robyn")
p_load(reactable)
p_load(DT)
p_load(plotly)

# 並列処理用（マルチコアの設定）
Sys.setenv(R_FUTURE_FORK_ENABLE = "true")
options(future.fork.enable = TRUE)

# モデリング関連のディレクトリ
path_model <- "model/"
```

# 追記予定

- サンプルコード

- 簡単な解説
